### ISSUE TITLE
PHP & JS language support

### ISSUE THREAD

**Issue by Vadiok** [ArtsiomCh/NestedBracketsColorer#1]
It will be great if you add support of PHP and JavaScript languages.
Rainbow Brackets plugin supports this languages but its coloring algorithm not as good as yours.

**Comment by ArtsiomCh** [comment]
Hi @Vadiok 
Could you tell me what kind of IDE you're using: PHPStorm, WebStorm, IDEA with some specific PHP and JS plugins, or something else? Ideally, if you can point me to the plugins responsible for parsing PHP and JS.
Also, as I'm not too familar with PHP and JS, let me know please what kind of brackets you are most interesting to be colored: rounds `)`, square `]`, angled `>`, braces `}`, etc.?

**Comment by Vadiok** [comment]
Hi @ArtsiomCh 

**IDE**
I'm using PhpStorm. If you're using IDEA, I think [PHP plugin](https://plugins.jetbrains.com/plugin/6610-php) will add supporting of PHP. JavaScript & TypeScript supported by only by Ultimate edition of IDEA, no plugins required.

**Brackets**
Most interesting is round brackets ``()``, also it will be good if square brackets will be supported for PHP arrays.

**PHP problem**
PHP is the HTML file with insertion of PHP code, example
```php
<?php
$name = isset($_GET['name']) ? $_GET['name'] : 'Unknown';
?>
<p> 
    Hello <?=mb_strtoupper(htmlspecialchars(trim($name))) ?> =:)
</p>
<?php
echo date('Y-m-d');
```
So it's required to add colors only in PHP constructions: ``<?php ... ?>`` & ``<?= ... ?>``, not in HTML. ``<?php`` can not to have closing tag ``?>`` in the end of file.

**Comment by ArtsiomCh** [comment]
@Vadiok please try new [0.1.0](https://github.com/ArtsiomCh/NestedBracketsColorer/blob/0.1.0/NestedBracketsColorer.jar) version with  PHP and JavaScript/TypeScript support added. And let me know if it works as desired before I submit it to  JetBrains Plugin Repository.

**Comment by Vadiok** [comment]
@ArtsiomCh thank you very much. It works as expected.

What I tested:
- PHP code: ``()`` & ``[]`` - braces coloring
- JS code: ``()`` & ``[]`` - braces coloring
- HTML code inside PHP files: braces not coloring
- Comments inside PHP & JS files: braces not coloring
- Escaped braces (example: ``\[``) skipped.
