### ISSUE TITLE
Support for Scala

### ISSUE THREAD

**Issue by MarioAriasC** [ArtsiomCh/NestedBracketsColorer#2]
Support for Scala should be easy to implement.

Cheers

**Comment by ArtsiomCh** [comment]
Yep, should not be a problem. Will do on weekend.

**Comment by ArtsiomCh** [comment]
Scala support added at version 0.3.0
@MarioAriasC you can wait a couple of days while update approved by JB, or you can use the direct link to download the update: [https://plugins.jetbrains.com/plugin/10210-nested-brackets-colorer/update/45575](https://plugins.jetbrains.com/plugin/10210-nested-brackets-colorer/update/45575)
