### ISSUE TITLE
Color/style customizations missing in Android Studio (OS X)

### ISSUE THREAD

**Issue by starkej2** [ArtsiomCh/NestedBracketsColorer#3]
I don't see the `Nested Brackets Colorer` option to customize colors/styles on the `Editor -> Color` Scheme screen.

Android Studio 3.1.2
macOS High Sierra 10.13.4

**Comment by starkej2** [comment]
Oh I was actually on v0.0.2 of the plugin. Any idea why the latest version (0.2.1) doesn't appear in the intellij plugin repository?

**Comment by ArtsiomCh** [comment]
IntelliJ do check for updates not on an everyday basis (looks like every week or two). 
So, to check  the latest version of plugins, you need to go `Settings->Appearens$Behavior->System Settings->Updates` and manually click the `Check Now ` button.
