### ISSUE TITLE
Suggestion:  Support arbitrary files

### ISSUE THREAD

**Issue by fuzzyweapon** [ArtsiomCh/NestedBracketsColorer#4]
I work a lot with files that aren't the actual languages supported by any editor.

It'd be nice if I could just register closing and ending character pairs and allow to associate a group of these with an extension (or arbitrary/no extension or recognized extension).

This would be useful for domain languages that do not implicitly use language features to make up the domain language.

**Comment by ArtsiomCh** [comment]
Hi! Thanks for suggestion. Unfortunately this is way out of scope for this plugin. That could be a good idea for another plugin. I'll see if I can find time to implement it or you can try to write plugin for that by yourself.
