### ISSUE TITLE
Suggestion:  A toggle for showing all "bracket" scopes

### ISSUE THREAD

**Issue by fuzzyweapon** [ArtsiomCh/NestedBracketsColorer#5]
It'd be nice if there was a mode where I could show all bracket scope highlights at once so I can spot errors in particularly nasty domain languages (or in-memory proprietary scripting languages).  For instance, try to figure out at a glance where the following code has missing pairs:

`
@dolist [filterbool(#lambda/and(not(member(#10 #13 #161 #163 #164 #175 #177,\%0)),not(member(Staff|Afk|Grid Alpha|Grid Beta,u(\%0/AREA),|))),[lsearch(*BSGBuilder,TYPE,ROOM)])]=think ===%r%r%i0%r---%r%r[lattrp()]
`

It's really easy to make mistakes while writing this kind of code as you're coding, but this suggested feature would go a long way for helping similar use cases.  Since this is a bracket heavy coding language, it would take a lot of time to keep checking all of the scopes individually while iterating.

Yes this is nasty.  Yes there are multiple code languages like this which will never change their pattern.  No I do not have control over this composition and it isn't wanted for running one off code like this (typically used to clean up attribute data for objects).  Encapsulating little parts of this type of one-off code (and cleaning it up after) is time-consuming.

**Comment by ArtsiomCh** [comment]
Hi! Thanks for suggestion. Unfortunately this is way out of scope for this plugin. That could be a good idea for another plugin. I'll see if I can find time to implement it or you can try to write plugin for that by yourself.
