### ISSUE TITLE
Crashes the intelliJ syntax highlighter

### ISSUE THREAD

**Issue by filippo-orru** [ArtsiomCh/NestedBracketsColorer#6]
Can't use the extension as when enabled it crashes the intelliJ syntax highlighting after <1s.

**Comment by ArtsiomCh** [comment]
Which version of idea and plugin you're using?

**Comment by filippo-orru** [comment]
IntelliJ IDEA 2022.1, Build #IU-221.5080.210, built on April 12, 2022. Plugin version 0.6.0. 
I am using [Rainbow Brackets](https://plugins.jetbrains.com/plugin/10080-rainbow-brackets) instead now.
