### ISSUE TITLE
Suggestion: Support for c# curly braces

### ISSUE THREAD

**Issue by garethterrace** [ArtsiomCh/NestedBracketsColorer#7]
A lot of people would shift to this plugin from Rainbow Brackets just for this. 

in c# if we could have support for nested curly braces `{ }` that'd make things perfection!

**Comment by ArtsiomCh** [comment]
Done in 0.7.1 version (should be available within business  2 days by JetBrains approval)
But remember, this is plugin developed mainly for my personal use in my spare time. 
So, **no commitments** for any new features, updates, bug-fixing and/or support. While Rainbow Brackets developers has such commitments at least for the paid features during the subscription period.
