### ISSUE TITLE
Blank monitor

### ISSUE THREAD

**Issue by emanuelefirmani** [ArtsiomCh/NestedBracketsColorer#9]
My monitor goes blank some in a while.
Issue is gone after disabling the plugin

**Comment by emanuelefirmani** [comment]
Using Rider 2023.2 on a Samsung 49'' monitor

**Comment by ArtsiomCh** [comment]
Please verify it's plugin related issue.
Try to enable/disable plugin few time and see if the issue is totally related to the plugin.
Also would be helpful to see the codebase the issue happened.
